---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: mapseq2biom
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::mgnify-pipelines-toolkit=0.1.1"
