---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "fastqsuffixheadercheck"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::mgnify-pipelines-toolkit=0.1.6"
